services:
  - type: web
    name: marketai-code4sud
    env: python
    plan: free
    buildCommand: pip install -r requirements_cloud.txt
    startCommand: gunicorn app_cloud:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PORT
        value: 10000
